# Site Settings
title: Calla Carter
email: callajun
description: >
  My site.
baseurl: ""
url: "http://127.0.0.1:4000/"
twitter_username: callajun
github_username:  callajun
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
