# Site Settings
title: Calla Carter
email: hi@callacarter.com
description: >
  My site.
baseurl: ""
url: "http://callacarter.com/"
twitter_username: callajun
github_username:  callajun
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
